// Array of questions grouped by category

const questions = [
  {
    category: "matematika",
    questions: [
      { question: "Berapakah hasil dari 8 x 7?", options: ["54", "56", "58", "60"], correctAnswer: 1 },
      { question: "Jika x + 5 = 12, maka nilai x adalah?", options: ["5", "6", "7", "8"], correctAnswer: 2 },
      { question: "Berapakah luas segitiga dengan alas 10 cm dan tinggi 6 cm?", options: ["30 cm²", "60 cm²", "90 cm²", "120 cm²"], correctAnswer: 0 },
      { question: "Hasil dari 25 ÷ 5 + 4 adalah?", options: ["8", "9", "10", "11"], correctAnswer: 1 },
      { question: "Bilangan prima antara 10 dan 20 adalah?", options: ["11, 13, 17, 19", "12, 14, 16, 18", "10, 12, 14, 20", "11, 15, 17, 18"], correctAnswer: 0 },
      { question: "Berapa hasil dari akar kuadrat dari 81?", options: ["7", "8", "9", "10"], correctAnswer: 2 },
      { question: "Nilai π (pi) mendekati berapa?", options: ["2.14", "3.14", "3.41", "4.13"], correctAnswer: 1 },
      { question: "Jika sebuah persegi memiliki sisi 6 cm, berapa kelilingnya?", options: ["24 cm", "36 cm", "12 cm", "18 cm"], correctAnswer: 0 },
      { question: "Berapakah hasil 15 x 4?", options: ["60", "50", "55", "65"], correctAnswer: 0 },
      { question: "Berapakah hasil dari 100 ÷ 25?", options: ["2", "3", "4", "5"], correctAnswer: 3 },
      { question: "Berapakah 2³?", options: ["6", "8", "4", "10"], correctAnswer: 1 },
      { question: "Sudut segitiga selalu berjumlah?", options: ["90°", "180°", "270°", "360°"], correctAnswer: 1 },
      { question: "Apa hasil dari 5²?", options: ["20", "25", "30", "35"], correctAnswer: 1 },
      { question: "Jika panjang 8 cm dan lebar 4 cm, berapakah luas persegi panjang?", options: ["32 cm²", "24 cm²", "36 cm²", "28 cm²"], correctAnswer: 0 },
      { question: "Berapa hasil dari 9 + 6 ÷ 3?", options: ["5", "11", "13", "15"], correctAnswer: 1 },
      { question: "Berapakah keliling lingkaran jika jari-jari 7 cm? (π = 22/7)", options: ["44 cm", "28 cm", "33 cm", "22 cm"], correctAnswer: 0 },
      { question: "Apa hasil dari 6! (faktorial 6)?", options: ["720", "120", "60", "180"], correctAnswer: 0 },
      { question: "Jika kamu membeli 3 buku seharga Rp20.000, berapa totalnya?", options: ["Rp50.000", "Rp60.000", "Rp40.000", "Rp30.000"], correctAnswer: 1 },
      { question: "Jika suhu naik 5 derajat dari 23°C, berapakah suhunya?", options: ["28°C", "29°C", "30°C", "31°C"], correctAnswer: 0 },
      { question: "Berapa hasil dari 7 x 8 - 4?", options: ["48", "52", "56", "60"], correctAnswer: 1 },
      { question: "Berapa hasil 5³?", options: ["100", "125", "150", "175"], correctAnswer: 1 },
      { question: "Jika kamu punya 5 apel dan temanmu memberi 3, berapa totalnya?", options: ["6", "7", "8", "9"], correctAnswer: 2 },
      { question: "Berapakah nilai dari 3² + 4²?", options: ["25", "26", "27", "28"], correctAnswer: 0 },
      { question: "Hasil dari 144 ÷ 12 adalah?", options: ["10", "11", "12", "13"], correctAnswer: 2 },
      { question: "Jika luas lingkaran adalah 314 cm² dan π = 3.14, berapakah jari-jari?", options: ["5", "7", "9", "10"], correctAnswer: 3 },
      { question: "Hasil dari 18 + 24 adalah?", options: ["40", "41", "42", "43"], correctAnswer: 0 },
      { question: "Berapa persen dari 50 adalah 10?", options: ["10%", "15%", "20%", "25%"], correctAnswer: 2 },
      { question: "Berapa jumlah sudut pada segi lima?", options: ["360°", "540°", "600°", "720°"], correctAnswer: 1 },
      { question: "Berapakah hasil dari 72 ÷ 8?", options: ["8", "9", "10", "11"], correctAnswer: 1 },
      { question: "Jika 2x = 18, berapakah x?", options: ["7", "8", "9", "10"], correctAnswer: 2 }
    ]
  },

  {
    category: "pengetahuan alam",
    questions: [
      { question: "Alat untuk mengukur suhu disebut?", options: ["Termometer", "Barometer", "Higrometer", "Altimeter"], correctAnswer: 0 },
      { question: "Proses perubahan air menjadi uap disebut?", options: ["Kondensasi", "Evaporasi", "Presipitasi", "Infiltrasi"], correctAnswer: 1 },
      { question: "Planet yang disebut planet merah adalah?", options: ["Mars", "Venus", "Merkurius", "Saturnus"], correctAnswer: 0 },
      { question: "Bagian tumbuhan yang berfungsi menyerap air adalah?", options: ["Akar", "Batang", "Daun", "Bunga"], correctAnswer: 0 },
      { question: "Makhluk hidup yang mampu membuat makanannya sendiri disebut?", options: ["Heterotrof", "Autotrof", "Konsumen", "Pengurai"], correctAnswer: 1 },
      { question: "Sumber energi utama bagi Bumi adalah?", options: ["Matahari", "Air", "Minyak", "Gas"], correctAnswer: 0 },
      { question: "Gas yang paling banyak di atmosfer Bumi adalah?", options: ["Oksigen", "Karbon Dioksida", "Nitrogen", "Hidrogen"], correctAnswer: 2 },
      { question: "Organ pernapasan pada ikan adalah?", options: ["Paru-paru", "Trakea", "Insang", "Kulit"], correctAnswer: 2 },
      { question: "Planet terbesar di tata surya adalah?", options: ["Bumi", "Mars", "Jupiter", "Venus"], correctAnswer: 2 },
      { question: "Air membeku pada suhu?", options: ["0°C", "100°C", "50°C", "10°C"], correctAnswer: 0 },
      { question: "Hewan yang berkembang biak dengan cara bertelur disebut?", options: ["Vivipar", "Ovipar", "Ovovivipar", "Metamorf"], correctAnswer: 1 },
      { question: "Apa alat pernapasan pada katak?", options: ["Kulit dan paru-paru", "Insang", "Trakea", "Paru-paru saja"], correctAnswer: 0 },
      { question: "Benda cair memiliki bentuk yang?", options: ["Tetap", "Berubah mengikuti wadah", "Kaku", "Tajam"], correctAnswer: 1 },
      { question: "Proses fotosintesis terjadi di bagian?", options: ["Akar", "Batang", "Daun", "Bunga"], correctAnswer: 2 },
      { question: "Apa yang dihasilkan dari fotosintesis?", options: ["Oksigen dan glukosa", "Karbon dan air", "Karbon dioksida dan energi", "Nitrogen dan uap"], correctAnswer: 0 },
      { question: "Tulang tengkorak berfungsi untuk?", options: ["Membentuk tubuh", "Melindungi otak", "Membantu bergerak", "Menopang tubuh"], correctAnswer: 1 },
      { question: "Benda gas memiliki bentuk dan volume yang?", options: ["Tetap", "Berubah", "Menyusut", "Meluas"], correctAnswer: 1 },
      { question: "Hewan pemakan tumbuhan disebut?", options: ["Karnivora", "Omnivora", "Herbivora", "Insektivora"], correctAnswer: 2 },
      { question: "Apa satuan kuat arus listrik?", options: ["Volt", "Ohm", "Ampere", "Watt"], correctAnswer: 2 },
      { question: "Bumi mengelilingi Matahari disebut?", options: ["Rotasi", "Revolusi", "Orbit", "Translasi"], correctAnswer: 1 },
      { question: "Lapisan atmosfer terdekat dengan bumi adalah?", options: ["Stratosfer", "Troposfer", "Mesosfer", "Termosfer"], correctAnswer: 1 },
      { question: "Alat untuk mengukur tekanan udara adalah?", options: ["Termometer", "Barometer", "Anemometer", "Altimeter"], correctAnswer: 1 },
      { question: "Apa organ utama sistem pencernaan manusia?", options: ["Jantung", "Lambung", "Hati", "Paru-paru"], correctAnswer: 1 },
      { question: "Lapisan ozon terdapat di?", options: ["Troposfer", "Mesosfer", "Stratosfer", "Termosfer"], correctAnswer: 2 },
      { question: "Bakteri adalah makhluk hidup bersel?", options: ["Satu", "Dua", "Tiga", "Banyak"], correctAnswer: 0 },
      { question: "Benda padat memiliki bentuk dan volume yang?", options: ["Tetap", "Berubah", "Menyusut", "Mencair"], correctAnswer: 0 },
      { question: "Bagian sel tumbuhan yang tidak dimiliki hewan adalah?", options: ["Nukleus", "Membran", "Kloroplas", "Sitoplasma"], correctAnswer: 2 },
      { question: "Apa fungsi akar pada tumbuhan?", options: ["Fotosintesis", "Pernapasan", "Menyerap air", "Reproduksi"], correctAnswer: 2 },
      { question: "Contoh perubahan kimia adalah?", options: ["Membekunya air", "Penguapan", "Pembakaran", "Pelelehan"], correctAnswer: 2 },
      { question: "Sumber energi terbarukan adalah?", options: ["Batu bara", "Minyak bumi", "Matahari", "Gas alam"], correctAnswer: 2 }
    ]
  },

  {
    category: "sejarah",
    questions: [
      { question: "Siapa proklamator kemerdekaan Indonesia?", options: ["Soekarno dan Hatta", "Sudirman dan Hatta", "Soekarno dan Soedirman", "Soekarno dan Sjahrir"], correctAnswer: 0 },
      { question: "Kapan Indonesia merdeka?", options: ["17 Agustus 1945", "17 Agustus 1946", "1 Juni 1945", "1 Januari 1945"], correctAnswer: 0 },
      { question: "Kerajaan Hindu tertua di Indonesia adalah?", options: ["Majapahit", "Sriwijaya", "Kutai", "Tarumanegara"], correctAnswer: 2 },
      { question: "Kerajaan Islam pertama di Indonesia adalah?", options: ["Demak", "Samudra Pasai", "Aceh", "Banten"], correctAnswer: 1 },
      { question: "Siapakah tokoh yang dikenal dengan sebutan Bapak Pendidikan Nasional?", options: ["Ki Hajar Dewantara", "Soekarno", "Moh. Hatta", "RA Kartini"], correctAnswer: 0 },
      { question: "Peristiwa Sumpah Pemuda terjadi pada tahun?", options: ["1926", "1927", "1928", "1929"], correctAnswer: 2 },
      { question: "RA Kartini dikenal sebagai pejuang di bidang?", options: ["Pendidikan", "Perdagangan", "Militer", "Olahraga"], correctAnswer: 0 },
      { question: "Apa nama organisasi pemuda yang mengucapkan Sumpah Pemuda?", options: ["Budi Utomo", "PPI", "Pemuda Indonesia", "Trikora"], correctAnswer: 2 },
      { question: "Siapakah presiden pertama Indonesia?", options: ["Soekarno", "Hatta", "Soeharto", "Habibie"], correctAnswer: 0 },
      { question: "Apa nama konstitusi Indonesia yang pertama?", options: ["UUD 1945", "RIS", "Konstitusi Sementara", "Dekrit Presiden"], correctAnswer: 0 },
      { question: "Dimana proklamasi dibacakan?", options: ["Jakarta", "Yogyakarta", "Bandung", "Surabaya"], correctAnswer: 0 },
      { question: "Apa nama naskah proklamasi yang asli?", options: ["Teks Proklamasi", "Naskah Soekarno", "Teks Kemerdekaan", "Piagam Jakarta"], correctAnswer: 0 },
      { question: "Kapan Soeharto naik menjadi presiden?", options: ["1965", "1966", "1967", "1968"], correctAnswer: 2 },
      { question: "Apa nama masa pemerintahan Soeharto?", options: ["Reformasi", "Orde Baru", "Orde Lama", "Demokrasi Terpimpin"], correctAnswer: 1 },
      { question: "Apa isi Sumpah Pemuda?", options: ["Satu bangsa, satu tanah air, satu bahasa", "Kemerdekaan penuh", "Demokrasi", "Kesatuan Indonesia"], correctAnswer: 0 },
      { question: "Apa nama masa awal kemerdekaan Indonesia?", options: ["Orde Lama", "Demokrasi Terpimpin", "Masa Revolusi", "Orde Baru"], correctAnswer: 2 },
      { question: "Apa tujuan BPUPKI?", options: ["Merancang dasar negara", "Merdeka", "Melawan Jepang", "Memilih presiden"], correctAnswer: 0 },
      { question: "Siapa ketua PPKI?", options: ["Soekarno", "Moh. Hatta", "Radjiman", "Soepomo"], correctAnswer: 1 },
      { question: "Dimana sidang PPKI pertama diadakan?", options: ["Jakarta", "Bogor", "Bandung", "Surabaya"], correctAnswer: 0 },
      { question: "Apa tujuan Sumpah Pemuda?", options: ["Persatuan dan kesatuan", "Merdeka", "Melawan penjajah", "Mendukung Soekarno"], correctAnswer: 0 },
      { question: "Apa nama partai pertama di Indonesia?", options: ["PNI", "Budi Utomo", "PKI", "Masyumi"], correctAnswer: 1 },
      { question: "Apa yang terjadi pada 10 November 1945?", options: ["Pertempuran Surabaya", "Proklamasi", "Sumpah Pemuda", "Agresi Belanda"], correctAnswer: 0 },
      { question: "Kapan agresi militer Belanda I terjadi?", options: ["1946", "1947", "1948", "1949"], correctAnswer: 1 },
      { question: "Siapa yang membentuk Tentara Keamanan Rakyat?", options: ["Soekarno", "Hatta", "Sudirman", "Soedirman"], correctAnswer: 0 },
      { question: "Apa tujuan Konferensi Meja Bundar?", options: ["Pengakuan kedaulatan", "Perundingan", "Membentuk RIS", "Demokrasi"], correctAnswer: 0 },
      { question: "Apa nama sistem pemerintahan awal Indonesia?", options: ["Parlementer", "Presidensial", "Demokrasi", "Monarki"], correctAnswer: 1 },
      { question: "Siapa wakil presiden pertama?", options: ["Soeharto", "Moh. Hatta", "Habibie", "Yusuf Kalla"], correctAnswer: 1 },
      { question: "Kapan pemilu pertama kali diadakan?", options: ["1955", "1950", "1960", "1949"], correctAnswer: 0 },
      { question: "Apa nama lambang negara Indonesia?", options: ["Garuda Pancasila", "Bendera Merah Putih", "Sang Saka", "Burung Merdeka"], correctAnswer: 0 },
      { question: "Apa nama ibu kota Indonesia saat agresi Belanda II?", options: ["Yogyakarta", "Jakarta", "Bandung", "Surabaya"], correctAnswer: 0 }
    ]
  },

  {
    category: "geografi",
    questions: [
      { question: "Ibukota Provinsi Jawa Barat adalah?", options: ["Bandung", "Bekasi", "Bogor", "Depok"], correctAnswer: 0 },
      { question: "Gunung tertinggi di Indonesia adalah?", options: ["Gunung Rinjani", "Gunung Semeru", "Gunung Kerinci", "Puncak Jaya"], correctAnswer: 3 },
      { question: "Laut yang memisahkan Pulau Sumatera dan Pulau Jawa adalah?", options: ["Laut Jawa", "Selat Sunda", "Selat Malaka", "Laut Flores"], correctAnswer: 1 },
      { question: "Pulau terbesar di Indonesia adalah?", options: ["Jawa", "Sumatera", "Kalimantan", "Sulawesi"], correctAnswer: 2 },
      { question: "Danau terbesar di Indonesia adalah?", options: ["Toba", "Maninjau", "Poso", "Sentani"], correctAnswer: 0 },
      { question: "Gunung Merapi terletak di provinsi?", options: ["Jawa Tengah", "Jawa Timur", "Yogyakarta", "Banten"], correctAnswer: 0 },
      { question: "Ibukota Indonesia adalah?", options: ["Jakarta", "Bandung", "Surabaya", "Yogyakarta"], correctAnswer: 0 },
      { question: "Pulau Bali terletak di sebelah timur pulau?", options: ["Jawa", "Sumatera", "Sulawesi", "Kalimantan"], correctAnswer: 0 },
      { question: "Negara tetangga Indonesia di utara adalah?", options: ["Malaysia", "Australia", "India", "Timor Leste"], correctAnswer: 0 },
      { question: "Benua terbesar di dunia adalah?", options: ["Asia", "Afrika", "Eropa", "Amerika"], correctAnswer: 0 },
      { question: "Samudra terluas di dunia adalah?", options: ["Atlantik", "Pasifik", "Hindia", "Arktik"], correctAnswer: 1 },
      { question: "Letak Indonesia secara astronomis berada di?", options: ["6°LU–11°LS dan 95°BT–141°BT", "10°LU–10°LS dan 100°BT–140°BT", "8°LU–8°LS dan 90°BT–150°BT", "5°LU–5°LS dan 90°BT–140°BT"], correctAnswer: 0 },
      { question: "Apa ibu kota negara Thailand?", options: ["Bangkok", "Hanoi", "Manila", "Kuala Lumpur"], correctAnswer: 0 },
      { question: "Sungai terpanjang di dunia adalah?", options: ["Amazon", "Nil", "Yangtze", "Mississippi"], correctAnswer: 1 },
      { question: "Gunung Fuji terletak di negara?", options: ["Cina", "Jepang", "Korea", "Vietnam"], correctAnswer: 1 },
      { question: "Kawasan Asia Tenggara terdiri dari berapa negara?", options: ["9", "10", "11", "12"], correctAnswer: 1 },
      { question: "Indonesia memiliki berapa provinsi?", options: ["32", "33", "34", "35"], correctAnswer: 2 },
      { question: "Apa ibu kota negara Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswer: 2 },
      { question: "Apa batas sebelah timur Indonesia?", options: ["Papua Nugini", "Timor Leste", "Samudra Pasifik", "Filipina"], correctAnswer: 0 },
      { question: "Iklim tropis ditandai oleh?", options: ["Hujan sepanjang tahun", "Musim dingin", "Kering sepanjang tahun", "Musim salju"], correctAnswer: 0 },
      { question: "Apa negara kepulauan terbesar di dunia?", options: ["Indonesia", "Filipina", "Jepang", "Maladewa"], correctAnswer: 0 },
      { question: "Letak geografis Indonesia di antara benua?", options: ["Asia dan Australia", "Asia dan Afrika", "Afrika dan Eropa", "Eropa dan Australia"], correctAnswer: 0 },
      { question: "Wilayah paling barat Indonesia adalah?", options: ["Sabang", "Aceh", "Riau", "Medan"], correctAnswer: 0 },
      { question: "Wilayah paling timur Indonesia adalah?", options: ["Merauke", "Papua", "Nusa Tenggara Timur", "Maluku"], correctAnswer: 0 },
      { question: "Letak Indonesia di antara samudra?", options: ["Hindia dan Pasifik", "Atlantik dan Pasifik", "Pasifik dan Arktik", "Atlantik dan Hindia"], correctAnswer: 0 },
      { question: "Negara di Asia Tenggara yang tidak memiliki laut?", options: ["Laos", "Vietnam", "Thailand", "Myanmar"], correctAnswer: 0 },
      { question: "Apa gunung tertinggi di Asia?", options: ["Fuji", "Everest", "Elbrus", "Kinabalu"], correctAnswer: 1 },
      { question: "Gunung Bromo terdapat di provinsi?", options: ["Jawa Timur", "Jawa Tengah", "Yogyakarta", "Banten"], correctAnswer: 0 },
      { question: "Apa nama ibukota negara Inggris?", options: ["London", "Paris", "Berlin", "Manchester"], correctAnswer: 0 },
      { question: "Apa gunung api teraktif di Indonesia?", options: ["Merapi", "Semeru", "Kelud", "Sinabung"], correctAnswer: 0 }
    ]
  },
];
